services:
  wordpress:
    image: wordpress:latest
    container_name: streetwolf-wp
    restart: always
    ports:
      - "8810:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: streetwolf_user
      WORDPRESS_DB_PASSWORD: streetwolf_password
      WORDPRESS_DB_NAME: streetwolf_db
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - streetwolf_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: streetwolf-mysql
    restart: always
    environment:
      MYSQL_DATABASE: streetwolf_db
      MYSQL_USER: streetwolf_user
      MYSQL_PASSWORD: streetwolf_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - streetwolf_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: streetwolf-phpmyadmin
    restart: always
    ports:
      - "8811:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - streetwolf_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  streetwolf_network:
    driver: bridge
